# Generated by Django 5.2.15 on 2026-06-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField()),
                ('objective', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign_name', models.CharField(blank=True, max_length=255, null=True)),
                ('audience_size', models.IntegerField(default=0)),
                ('communications_generated', models.IntegerField(default=0)),
                ('receipt_events_processed', models.IntegerField(default=0)),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
