# Generated by Django 5.2.15 on 2026-06-10 18:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignexecution',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignexecution',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignexecution',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaignexecution',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('PARTIAL_SUCCESS', 'Partial Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=20),
        ),
    ]
