"""
insight_engine/insight_engine.py
==================================
Aether CRM – Insights Engine
------------------------------
Responsible for one thing: consume the append-only communication receipt log
produced by the Receipt API, compute deterministic campaign and channel
performance metrics, generate rule-based business recommendations, and surface
human-readable summaries for marketers and downstream systems.

This module sits at the terminal stage of the Aether CRM execution pipeline.
It does NOT send messages, simulate delivery, generate communications, select
audiences, or modify any receipt record.  Those responsibilities belong
exclusively to their respective upstream modules.

Pipeline position
-----------------
Goal Parser
  ↓
Audience Selector
  ↓
Campaign Planner
  ↓
Communication Manager
  ↓
Channel Service
  ↓
Receipt API
  ↓
Insights Engine  ← THIS MODULE

Read-only guarantee
--------------------
The Insights Engine never writes to, reorders, or deletes receipt records.
All receipt data is treated as immutable input consumed from the append-only
event log maintained by the Receipt API.  Any attempt to modify receipt
storage from within this module is a contract violation.

Determinism guarantee
---------------------
All metrics and recommendations are derived exclusively from the receipt CSV
via deterministic arithmetic.  Given identical input data, the Insights Engine
always produces identical outputs regardless of when or where this module runs.

Metric definitions
------------------
The following formulae govern all campaign-level and channel-level metric
calculations.  These definitions are immutable in V1 and must not be changed
without a corresponding ProjectDecision.md entry.

    delivery_rate  = DELIVERED  / DISPATCHED  × 100
    open_rate      = (OPENED + READ) / DELIVERED × 100
    click_rate     = CLICKED    / DELIVERED    × 100
    failure_rate   = FAILED     / DISPATCHED   × 100

Division-by-zero is handled gracefully: any rate whose denominator is zero
is reported as 0.0 rather than raising an exception.

Channel inference
-----------------
Receipt records produced by the Receipt API do not include a channel column.
The Insights Engine infers channel from the communication_id prefix pattern
established by the Channel Service smoke-test convention and the Communication
Manager's naming contract:

    communication_id prefix   →  channel
    ─────────────────────────────────────
    COMM-CH-EMAIL-*           →  EMAIL
    COMM-CH-SMS-*             →  SMS
    COMM-CH-PUSH-*            →  PUSH
    COMM-CH-WA-*              →  WHATSAPP
    (no match)                →  UNKNOWN

For receipt logs generated by the full pipeline (Communication Manager →
Channel Service), the communication_id may carry a different prefix.  In those
cases the engine falls back gracefully to UNKNOWN rather than raising an error.
The Insights Engine also supports an optional communications DataFrame containing communication_id and channel columns. When supplied, this mapping takes precedence over prefix-based inference. Prefix inference remains the fallback mechanism for standalone execution and smoke tests.

Recommendation thresholds (V1, LOCKED)
---------------------------------------
    delivery_rate  < 80 %  →  Investigate channel delivery issues.
    delivery_rate  ≥ 90 %  →  Delivery performance is healthy.
    open_rate      < 20 %  →  Consider revising messaging content or subject lines.
    open_rate      ≥ 40 %  →  Audience engagement is strong; content is resonating.
    click_rate     < 5  %  →  Call-to-action copy or offer may need improvement.
    click_rate     > 15 %  →  Campaign engagement is strong; consider scaling.
    failure_rate   > 20 %  →  High failure rates detected. Review channel strategy.
    failure_rate   > 10 %  →  Elevated failure rate. Monitor channel health closely.

Django integration notes
------------------------
All public functions return either primitive Python types (dict, list) or
pandas DataFrames.  DataFrames can be converted to Django model querysets via
``DataFrame.to_dict(orient="records")`` without modification.  No Django
imports are present; the module is framework-agnostic by design.

Usage
-----
Run as a standalone script (demo / smoke-test mode):

    python insight_engine/insight_engine.py

Or import and call programmatically:

    from insight_engine.insight_engine import (
        load_receipts,
        calculate_campaign_metrics,
        calculate_channel_metrics,
        generate_recommendations,
        print_summary,
    )

    receipts     = load_receipts("path/to/communication_receipts.csv")
    camp_metrics = calculate_campaign_metrics(receipts)
    chan_metrics = calculate_channel_metrics(receipts)
    recs         = generate_recommendations(camp_metrics)
    print_summary(camp_metrics, chan_metrics, recs)
"""

from __future__ import annotations

import os
import sys
from typing import Any

import pandas as pd

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Default path to the receipt log, consistent with Receipt API convention.
# Override via the AETHER_RECEIPTS_PATH environment variable.
DEFAULT_RECEIPTS_PATH: str = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "data_generation",
    "data",
    "communication_receipts.csv",
)

# Canonical column schema expected in every receipts DataFrame consumed by
# this module.  This mirrors RECEIPT_COLUMNS in receipt_api.py and must
# remain in sync with the Receipt API contract.
RECEIPT_COLUMNS: list[str] = [
    "receipt_id",
    "communication_id",
    "campaign_id",
    "event",
    "event_timestamp",
]

# Columns emitted by calculate_channel_metrics().  Listed explicitly so
# downstream consumers can rely on a stable schema contract.
CHANNEL_METRIC_COLUMNS: list[str] = [
    "channel",
    "communications",
    "delivery_rate",
    "open_rate",
    "click_rate",
    "failure_rate",
]

# Complete set of supported lifecycle events (mirrors Receipt API).
VALID_EVENTS: set[str] = {
    "DISPATCHED",
    "DELIVERED",
    "FAILED",
    "OPENED",
    "READ",
    "CLICKED",
}

# ---------------------------------------------------------------------------
# Recommendation thresholds (V1, LOCKED)
# Changing these values requires a corresponding ProjectDecision.md entry.
# ---------------------------------------------------------------------------

_DELIVERY_RATE_CRITICAL_THRESHOLD: float  = 80.0   # Below this → critical alert.
_DELIVERY_RATE_HEALTHY_THRESHOLD:  float  = 90.0   # Above this → positive signal.
_OPEN_RATE_LOW_THRESHOLD:          float  = 20.0   # Below this → content review.
_OPEN_RATE_HIGH_THRESHOLD:         float  = 40.0   # Above this → positive signal.
_CLICK_RATE_LOW_THRESHOLD:         float  =  5.0   # Below this → CTA review.
_CLICK_RATE_HIGH_THRESHOLD:        float  = 15.0   # Above this → scale campaign.
_FAILURE_RATE_CRITICAL_THRESHOLD:  float  = 20.0   # Above this → urgent review.
_FAILURE_RATE_ELEVATED_THRESHOLD:  float  = 10.0   # Above this → monitor closely.

# ---------------------------------------------------------------------------
# Channel inference map
# Derived from the communication_id naming conventions established across
# the Communication Manager and Channel Service smoke tests.
# ---------------------------------------------------------------------------

_CHANNEL_PREFIX_MAP: dict[str, str] = {
    "COMM-CH-EMAIL-": "EMAIL",
    "COMM-CH-SMS-":   "SMS",
    "COMM-CH-PUSH-":  "PUSH",
    "COMM-CH-WA-":    "WHATSAPP",
}

_UNKNOWN_CHANNEL: str = "UNKNOWN"


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _safe_rate(numerator: float, denominator: float) -> float:
    """Compute a percentage rate, returning 0.0 when the denominator is zero.

    This guard prevents ZeroDivisionError across all metric calculations
    and ensures that campaigns or channels with no dispatched communications
    produce a 0.0 rate rather than raising an exception.

    Parameters
    ----------
    numerator:
        The count forming the numerator of the rate expression.
    denominator:
        The count forming the denominator of the rate expression.

    Returns
    -------
    float
        ``(numerator / denominator) * 100`` rounded to two decimal places,
        or ``0.0`` if ``denominator`` is zero.
    """
    if denominator == 0:
        return 0.0
    return round((numerator / denominator) * 100, 2)


def _infer_channel(communication_id: str) -> str:
    """Infer the delivery channel from a communication_id prefix.

    The Channel Service and Communication Manager encode channel information
    in the communication_id using a structured prefix convention.  This
    function decodes that convention deterministically.

    Parameters
    ----------
    communication_id:
        The communication identifier to inspect.

    Returns
    -------
    str
        The inferred channel name (e.g. ``"EMAIL"``), or ``"UNKNOWN"`` if no
        known prefix matches.

    Notes
    -----
    The prefix map is defined in ``_CHANNEL_PREFIX_MAP`` and must be kept in
    sync with the naming conventions used by the Communication Manager and the
    Channel Service smoke test.
    """
    for prefix, channel in _CHANNEL_PREFIX_MAP.items():
        if communication_id.startswith(prefix):
            return channel
    return _UNKNOWN_CHANNEL


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------


def load_receipts(path: str | None = None) -> pd.DataFrame:
    """Load communication receipt records from CSV.

    This is the sole data-ingestion entry point for the Insights Engine.
    It resolves the storage path, validates the schema, and returns a clean
    DataFrame ready for metric calculation.

    If the receipts file does not yet exist — for example, during early
    development or in a fresh environment — the function returns an empty
    DataFrame with the correct column schema so all downstream callers can
    proceed without branching on file existence.

    Parameters
    ----------
    path:
        Absolute or relative path to the receipts CSV.  When ``None``,
        the function first checks the ``AETHER_RECEIPTS_PATH`` environment
        variable and then falls back to ``DEFAULT_RECEIPTS_PATH``.

    Returns
    -------
    pd.DataFrame
        DataFrame containing all historical receipt records with columns
        ``receipt_id``, ``communication_id``, ``campaign_id``, ``event``,
        and ``event_timestamp``.  Returns an empty DataFrame with the same
        schema if the file does not exist.  All columns are string-typed
        for consistency with the Receipt API's storage contract.

    Raises
    ------
    ValueError
        If the file exists but is missing one or more required columns.
        The error message enumerates every missing column name.
    """
    resolved_path: str = (
        path
        or os.environ.get("AETHER_RECEIPTS_PATH", "")
        or DEFAULT_RECEIPTS_PATH
    )

    if not os.path.isfile(resolved_path):
        return pd.DataFrame(columns=RECEIPT_COLUMNS)

    df: pd.DataFrame = pd.read_csv(resolved_path, dtype=str)

    # Strip surrounding whitespace from every string cell to guard against
    # CSV editors or operating systems that introduce invisible characters.
    df = df.apply(lambda col: col.str.strip() if col.dtype == object else col)

    missing_cols: set[str] = set(RECEIPT_COLUMNS) - set(df.columns)
    if missing_cols:
        raise ValueError(
            f"[load_receipts] Receipts CSV at '{resolved_path}' is missing "
            f"required column(s): {sorted(missing_cols)}.  "
            f"Expected: {RECEIPT_COLUMNS}"
        )

    return df[RECEIPT_COLUMNS]


# ---------------------------------------------------------------------------
# Campaign-level metrics
# ---------------------------------------------------------------------------


def calculate_campaign_metrics(receipts: pd.DataFrame) -> dict[str, Any]:
    """Calculate aggregate campaign performance metrics from receipt records.

    Computes delivery, engagement, and failure rates across all campaigns
    represented in the receipt log.  All rates conform to the metric
    definitions documented in the module docstring.

    Parameters
    ----------
    receipts:
        DataFrame of receipt records as returned by ``load_receipts()``.
        Must contain at minimum the ``communication_id`` and ``event``
        columns.  An empty DataFrame is accepted and produces zero-value
        metrics.

    Returns
    -------
    dict[str, Any]
        A flat dictionary with the following keys:

        ``total_communications`` (int)
            Unique communication IDs observed across all receipts.
        ``total_receipts`` (int)
            Total number of receipt rows in the input DataFrame.
        ``delivery_rate`` (float)
            Percentage of dispatched communications that were delivered.
        ``open_rate`` (float)
            Percentage of delivered communications that were opened or read.
        ``click_rate`` (float)
            Percentage of delivered communications that were clicked.
        ``failure_rate`` (float)
            Percentage of dispatched communications that failed.

    Notes
    -----
    - All rate values are expressed as percentages (0.0 – 100.0).
    - Division-by-zero is handled via ``_safe_rate``; zero denominators
      produce 0.0 rather than raising an exception.
    - ``open_rate`` combines both OPENED and READ events because different
      channels report engagement differently (EMAIL emits OPENED; SMS and
      WHATSAPP emit READ).
    """
    if receipts.empty:
        return {
            "total_communications": 0,
            "total_receipts":       0,
            "delivery_rate":        0.0,
            "open_rate":            0.0,
            "click_rate":           0.0,
            "failure_rate":         0.0,
        }

    event_counts: pd.Series = receipts["event"].value_counts()

    dispatched: int = int(event_counts.get("DISPATCHED", 0))
    delivered:  int = int(event_counts.get("DELIVERED",  0))
    failed:     int = int(event_counts.get("FAILED",     0))
    opened:     int = int(event_counts.get("OPENED",     0))
    read:       int = int(event_counts.get("READ",       0))
    clicked:    int = int(event_counts.get("CLICKED",    0))

    total_communications: int = receipts["communication_id"].nunique()
    total_receipts:       int = len(receipts)

    delivery_rate: float = _safe_rate(delivered, dispatched)
    open_rate:     float = _safe_rate(opened + read, delivered)
    click_rate:    float = _safe_rate(clicked, delivered)
    failure_rate:  float = _safe_rate(failed, dispatched)

    return {
        "total_communications": total_communications,
        "total_receipts":       total_receipts,
        "delivery_rate":        delivery_rate,
        "open_rate":            open_rate,
        "click_rate":           click_rate,
        "failure_rate":         failure_rate,
    }


# ---------------------------------------------------------------------------
# Channel-level metrics
# ---------------------------------------------------------------------------


def calculate_channel_metrics(receipts: pd.DataFrame, communications: pd.DataFrame | None = None) -> pd.DataFrame:
    """Calculate per-channel performance metrics from receipt records.

    Groups receipt events by inferred channel and computes the same metric
    set as ``calculate_campaign_metrics()`` for each channel independently.
    Channel is inferred from the ``communication_id`` prefix using the
    convention documented in the module docstring.

    Parameters
    ----------
    receipts:
        DataFrame of receipt records as returned by ``load_receipts()``.
        An empty DataFrame is accepted and produces an empty output
        DataFrame with the correct column schema.
    communications:
        Optional communications DataFrame containing at minimum the
        ``communication_id`` and ``channel`` columns. When provided,
        channel values are resolved directly from this DataFrame rather
        than inferred from communication_id prefixes.

    Returns
    -------
    pd.DataFrame
        One row per inferred channel, with columns:

        ``channel`` (str)
            Channel name (EMAIL, SMS, PUSH, WHATSAPP, or UNKNOWN).
        ``communications`` (int)
            Number of unique communication IDs dispatched on this channel.
        ``delivery_rate`` (float)
            Percentage of dispatched communications delivered on this channel.
        ``open_rate`` (float)
            Percentage of delivered communications opened or read per channel.
        ``click_rate`` (float)
            Percentage of delivered communications clicked per channel.
        ``failure_rate`` (float)
            Percentage of dispatched communications that failed per channel.

        The DataFrame is sorted by ``delivery_rate`` descending so the
        strongest-performing channel appears first.

    Notes
    -----
    - Channels with zero dispatched events produce 0.0 for all rate columns.
    - When a communications DataFrame is provided, explicit channel mappings take precedence over prefix inference.
    - An ``UNKNOWN`` channel row is included when communication_ids cannot be resolved through either mechanism, preserving full receipt coverage in the output.
    """
    if receipts.empty:
        return pd.DataFrame(columns=CHANNEL_METRIC_COLUMNS)

    receipts_with_channel: pd.DataFrame = receipts.copy()

    if communications is not None:
        required_cols: set[str] = {"communication_id", "channel"}
        missing_cols: set[str] = required_cols - set(communications.columns)

        if missing_cols:
            raise ValueError(
                "[calculate_channel_metrics] Communications DataFrame is "
                f"missing required columns: {sorted(missing_cols)}"
            )

        channel_lookup: dict[str, str] = (
            communications[["communication_id", "channel"]]
            .drop_duplicates(subset=["communication_id"])
            .assign(channel=lambda df: df["channel"].astype(str).str.strip().str.upper())
            .set_index("communication_id")["channel"]
            .to_dict()
        )

        receipts_with_channel["channel"] = receipts_with_channel[
            "communication_id"
        ].map(channel_lookup)

        receipts_with_channel["channel"] = receipts_with_channel[
            "channel"
        ].fillna(
            receipts_with_channel["communication_id"].apply(_infer_channel)
        )
    else:
        receipts_with_channel["channel"] = receipts_with_channel[
            "communication_id"
        ].apply(_infer_channel)

    channel_rows: list[dict[str, Any]] = []

    for channel, group in receipts_with_channel.groupby("channel", sort=False):
        event_counts: pd.Series = group["event"].value_counts()

        dispatched: int = int(event_counts.get("DISPATCHED", 0))
        delivered:  int = int(event_counts.get("DELIVERED",  0))
        failed:     int = int(event_counts.get("FAILED",     0))
        opened:     int = int(event_counts.get("OPENED",     0))
        read:       int = int(event_counts.get("READ",       0))
        clicked:    int = int(event_counts.get("CLICKED",    0))

        communications: int = group["communication_id"].nunique()

        channel_rows.append(
            {
                "channel":       channel,
                "communications": communications,
                "delivery_rate":  _safe_rate(delivered, dispatched),
                "open_rate":      _safe_rate(opened + read, delivered),
                "click_rate":     _safe_rate(clicked, delivered),
                "failure_rate":   _safe_rate(failed, dispatched),
            }
        )

    result: pd.DataFrame = (
        pd.DataFrame(channel_rows, columns=CHANNEL_METRIC_COLUMNS)
        .sort_values("delivery_rate", ascending=False)
        .reset_index(drop=True)
    )

    return result


# ---------------------------------------------------------------------------
# Recommendation engine
# ---------------------------------------------------------------------------


def generate_recommendations(metrics: dict[str, Any]) -> list[str]:
    """Generate deterministic business recommendations from campaign metrics.

    Applies a fixed rule set to the metric dictionary produced by
    ``calculate_campaign_metrics()``.  Every threshold and the
    recommendation text it triggers are locked in V1; changes require a
    corresponding ProjectDecision.md entry.

    At least one recommendation is always returned.  If no rule thresholds
    are breached and no positive signals are detected, a neutral baseline
    recommendation is appended as a fallback, guaranteeing a non-empty list.

    Parameters
    ----------
    metrics:
        Dictionary as returned by ``calculate_campaign_metrics()``.  Must
        contain ``delivery_rate``, ``open_rate``, ``click_rate``, and
        ``failure_rate`` keys with float values in the [0.0, 100.0] range.

    Returns
    -------
    list[str]
        An ordered list of human-readable recommendation strings, each
        describing one actionable business insight.  The list always
        contains at least one entry.

    Raises
    ------
    KeyError
        If any required metric key is absent from the input dictionary.

    Notes
    -----
    Recommendations are evaluated independently; multiple rules may fire
    for the same metrics snapshot.  The order reflects severity: critical
    alerts appear before improvement suggestions, which appear before
    positive signals.
    """
    delivery_rate: float = metrics["delivery_rate"]
    open_rate:     float = metrics["open_rate"]
    click_rate:    float = metrics["click_rate"]
    failure_rate:  float = metrics["failure_rate"]

    recommendations: list[str] = []

    # ── Critical alerts (highest priority) ──────────────────────────────────

    if failure_rate > _FAILURE_RATE_CRITICAL_THRESHOLD:
        recommendations.append(
            f"High failure rate detected ({failure_rate:.1f}%). "
            "Review channel strategy and provider reliability immediately."
        )

    if delivery_rate < _DELIVERY_RATE_CRITICAL_THRESHOLD:
        recommendations.append(
            f"Delivery rate is below threshold ({delivery_rate:.1f}% vs "
            f"{_DELIVERY_RATE_CRITICAL_THRESHOLD:.0f}% minimum). "
            "Investigate channel delivery issues and audience data quality."
        )

    # ── Elevated warnings ────────────────────────────────────────────────────

    if (
        _FAILURE_RATE_ELEVATED_THRESHOLD < failure_rate
        <= _FAILURE_RATE_CRITICAL_THRESHOLD
    ):
        recommendations.append(
            f"Elevated failure rate observed ({failure_rate:.1f}%). "
            "Monitor channel health closely and review suppression lists."
        )

    # ── Improvement suggestions ──────────────────────────────────────────────

    if open_rate < _OPEN_RATE_LOW_THRESHOLD:
        recommendations.append(
            f"Open rate is low ({open_rate:.1f}% vs "
            f"{_OPEN_RATE_LOW_THRESHOLD:.0f}% benchmark). "
            "Consider revising subject lines, send times, or message preview text."
        )

    if click_rate < _CLICK_RATE_LOW_THRESHOLD:
        recommendations.append(
            f"Click-through rate is below benchmark ({click_rate:.1f}% vs "
            f"{_CLICK_RATE_LOW_THRESHOLD:.0f}% target). "
            "Review call-to-action copy, offer clarity, and landing page relevance."
        )

    # ── Positive signals ─────────────────────────────────────────────────────

    if delivery_rate >= _DELIVERY_RATE_HEALTHY_THRESHOLD:
        recommendations.append(
            f"Delivery performance is healthy ({delivery_rate:.1f}%). "
            "Channel infrastructure and audience data quality are sound."
        )

    if open_rate >= _OPEN_RATE_HIGH_THRESHOLD:
        recommendations.append(
            f"Audience engagement is strong ({open_rate:.1f}% open rate). "
            "Message content is resonating with this segment."
        )

    if click_rate > _CLICK_RATE_HIGH_THRESHOLD:
        recommendations.append(
            f"Campaign engagement is exceptionally strong ({click_rate:.1f}% "
            "click rate). Consider scaling budget, audience, or send frequency."
        )

    # ── Fallback (guarantee at least one recommendation) ─────────────────────

    if not recommendations:
        recommendations.append(
            "Campaign metrics are within normal operating ranges. "
            "Continue monitoring delivery and engagement trends across segments."
        )

    return recommendations


# ---------------------------------------------------------------------------
# Summary printer
# ---------------------------------------------------------------------------


def print_summary(
    campaign_metrics: dict[str, Any],
    channel_metrics:  pd.DataFrame,
    recommendations:  list[str],
) -> None:
    """Print a structured, human-readable campaign performance summary.

    Formats and writes the complete insights output to stdout in a style
    consistent with the Receipt API and Channel Service summary functions.
    The output is intentionally terminal-friendly for development and
    smoke-test contexts; Django views should consume the structured return
    values from the calculation functions directly.

    Parameters
    ----------
    campaign_metrics:
        Dictionary as returned by ``calculate_campaign_metrics()``.
    channel_metrics:
        DataFrame as returned by ``calculate_channel_metrics()``.
    recommendations:
        List of recommendation strings as returned by
        ``generate_recommendations()``.

    Returns
    -------
    None
        This function has no return value.  All output is written to stdout.
    """
    bar: str = "─" * 60

    # ── Header ───────────────────────────────────────────────────────────────

    print(f"\n{'=' * 60}")
    print("  AETHER CRM – Insights Engine Report")
    print(f"{'=' * 60}")

    # ── Campaign-level metrics ────────────────────────────────────────────────

    print(f"\n{bar}")
    print("  Campaign Performance Metrics")
    print(bar)
    print(
        f"  {'Total Communications':<30}  "
        f"{campaign_metrics['total_communications']:>8,}"
    )
    print(
        f"  {'Total Receipt Events':<30}  "
        f"{campaign_metrics['total_receipts']:>8,}"
    )
    print(
        f"  {'Delivery Rate':<30}  "
        f"{campaign_metrics['delivery_rate']:>7.1f} %"
    )
    print(
        f"  {'Open Rate':<30}  "
        f"{campaign_metrics['open_rate']:>7.1f} %"
    )
    print(
        f"  {'Click Rate':<30}  "
        f"{campaign_metrics['click_rate']:>7.1f} %"
    )
    print(
        f"  {'Failure Rate':<30}  "
        f"{campaign_metrics['failure_rate']:>7.1f} %"
    )

    # ── Channel-level metrics ─────────────────────────────────────────────────

    print(f"\n{bar}")
    print("  Channel Performance Metrics")
    print(bar)

    if channel_metrics.empty:
        print("  No channel data available.")
    else:
        # Column headers
        print(
            f"  {'Channel':<12}  {'Comms':>6}  {'Delivered':>9}  "
            f"{'Opened':>7}  {'Clicked':>7}  {'Failed':>7}"
        )
        print(f"  {'─' * 12}  {'─' * 6}  {'─' * 9}  {'─' * 7}  {'─' * 7}  {'─' * 7}")

        for _, row in channel_metrics.iterrows():
            print(
                f"  {row['channel']:<12}  "
                f"{int(row['communications']):>6,}  "
                f"{row['delivery_rate']:>8.1f}%  "
                f"{row['open_rate']:>6.1f}%  "
                f"{row['click_rate']:>6.1f}%  "
                f"{row['failure_rate']:>6.1f}%"
            )

    # ── Recommendations ───────────────────────────────────────────────────────

    print(f"\n{bar}")
    print("  Business Recommendations")
    print(bar)

    for idx, rec in enumerate(recommendations, start=1):
        # Wrap long recommendations at 56 characters to keep output readable
        # in standard 80-column terminals.
        words:   list[str] = rec.split()
        lines:   list[str] = []
        current: str       = ""

        for word in words:
            if len(current) + len(word) + 1 > 56:
                lines.append(current)
                current = word
            else:
                current = f"{current} {word}".strip()
        if current:
            lines.append(current)

        prefix: str = f"  {idx}. "
        indent: str = " " * len(prefix)
        print(prefix + lines[0])
        for continuation in lines[1:]:
            print(indent + continuation)

    # ── Footer ────────────────────────────────────────────────────────────────

    print(f"\n{'=' * 60}\n")


# ---------------------------------------------------------------------------
# Entry point (demo / smoke-test)
# ---------------------------------------------------------------------------


def main() -> None:
    """Execute a self-contained smoke test of the Insights Engine.

    Builds a synthetic receipt log covering all four supported channels
    and a representative spread of lifecycle events, then exercises every
    public function in the module.  All assertions are evaluated inline and
    any failure is reported immediately via ``AssertionError``.

    Smoke-test scenarios
    --------------------
    COMM-CH-EMAIL-00001 : DISPATCHED → DELIVERED → OPENED → CLICKED
    COMM-CH-EMAIL-00002 : DISPATCHED → DELIVERED → OPENED
    COMM-CH-EMAIL-00003 : DISPATCHED → FAILED
    COMM-CH-SMS-000004  : DISPATCHED → DELIVERED → READ → CLICKED
    COMM-CH-SMS-000005  : DISPATCHED → DELIVERED
    COMM-CH-PUSH-000006 : DISPATCHED → DELIVERED → OPENED
    COMM-CH-PUSH-000007 : DISPATCHED → FAILED
    COMM-CH-WA-0000008  : DISPATCHED → DELIVERED → READ → CLICKED
    COMM-CH-WA-0000009  : DISPATCHED → DELIVERED → READ
    COMM-CH-WA-0000010  : DISPATCHED → DELIVERED

    This module does not import any other Aether CRM module at runtime,
    keeping insight_engine.py independently executable during development
    and CI.
    """
    print("\n" + "=" * 60)
    print("  AETHER CRM – Insights Engine Smoke Test")
    print("=" * 60)

    # ------------------------------------------------------------------
    # 0. Build synthetic receipt records.
    #    IDs and timestamps are fixed so the smoke test is fully
    #    reproducible across environments.
    # ------------------------------------------------------------------

    DEMO_CAMPAIGN_ID: str = "CAMP-INSIGHT-TEST001"
    BASE_TS: str          = "2026-06-10T10:00:00Z"

    raw_receipts: list[dict[str, str]] = [
        # EMAIL full funnel
        {"receipt_id": "RCPT-TEST-00001", "communication_id": "COMM-CH-EMAIL-00001",
         "campaign_id": DEMO_CAMPAIGN_ID, "event": "DISPATCHED", "event_timestamp": BASE_TS},
        {"receipt_id": "RCPT-TEST-00002", "communication_id": "COMM-CH-EMAIL-00001",
         "campaign_id": DEMO_CAMPAIGN_ID, "event": "DELIVERED",  "event_timestamp": BASE_TS},
        {"receipt_id": "RCPT-TEST-00003", "communication_id": "COMM-CH-EMAIL-00001",
         "campaign_id": DEMO_CAMPAIGN_ID, "event": "OPENED",     "event_timestamp": BASE_TS},
        {"receipt_id": "RCPT-TEST-00004", "communication_id": "COMM-CH-EMAIL-00001",
         "campaign_id": DEMO_CAMPAIGN_ID, "event": "CLICKED",    "event_timestamp": BASE_TS},
        # EMAIL delivered + opened
        {"receipt_id": "RCPT-TEST-00005", "communication_id": "COMM-CH-EMAIL-00002",
         "campaign_id": DEMO_CAMPAIGN_ID, "event": "DISPATCHED", "event_timestamp": BASE_TS},
        {"receipt_id": "RCPT-TEST-00006", "communication_id": "COMM-CH-EMAIL-00002",
         "campaign_id": DEMO_CAMPAIGN_ID, "event": "DELIVERED",  "event_timestamp": BASE_TS},
        {"receipt_id": "RCPT-TEST-00007", "communication_id": "COMM-CH-EMAIL-00002",
         "campaign_id": DEMO_CAMPAIGN_ID, "event": "OPENED",     "event_timestamp": BASE_TS},
        # EMAIL failed
        {"receipt_id": "RCPT-TEST-00008", "communication_id": "COMM-CH-EMAIL-00003",
         "campaign_id": DEMO_CAMPAIGN_ID, "event": "DISPATCHED", "event_timestamp": BASE_TS},
        {"receipt_id": "RCPT-TEST-00009", "communication_id": "COMM-CH-EMAIL-00003",
         "campaign_id": DEMO_CAMPAIGN_ID, "event": "FAILED",     "event_timestamp": BASE_TS},
        # SMS full funnel
        {"receipt_id": "RCPT-TEST-00010", "communication_id": "COMM-CH-SMS-000004",
         "campaign_id": DEMO_CAMPAIGN_ID, "event": "DISPATCHED", "event_timestamp": BASE_TS},
        {"receipt_id": "RCPT-TEST-00011", "communication_id": "COMM-CH-SMS-000004",
         "campaign_id": DEMO_CAMPAIGN_ID, "event": "DELIVERED",  "event_timestamp": BASE_TS},
        {"receipt_id": "RCPT-TEST-00012", "communication_id": "COMM-CH-SMS-000004",
         "campaign_id": DEMO_CAMPAIGN_ID, "event": "READ",       "event_timestamp": BASE_TS},
        {"receipt_id": "RCPT-TEST-00013", "communication_id": "COMM-CH-SMS-000004",
         "campaign_id": DEMO_CAMPAIGN_ID, "event": "CLICKED",    "event_timestamp": BASE_TS},
        # SMS delivered only
        {"receipt_id": "RCPT-TEST-00014", "communication_id": "COMM-CH-SMS-000005",
         "campaign_id": DEMO_CAMPAIGN_ID, "event": "DISPATCHED", "event_timestamp": BASE_TS},
        {"receipt_id": "RCPT-TEST-00015", "communication_id": "COMM-CH-SMS-000005",
         "campaign_id": DEMO_CAMPAIGN_ID, "event": "DELIVERED",  "event_timestamp": BASE_TS},
        # PUSH delivered + opened
        {"receipt_id": "RCPT-TEST-00016", "communication_id": "COMM-CH-PUSH-000006",
         "campaign_id": DEMO_CAMPAIGN_ID, "event": "DISPATCHED", "event_timestamp": BASE_TS},
        {"receipt_id": "RCPT-TEST-00017", "communication_id": "COMM-CH-PUSH-000006",
         "campaign_id": DEMO_CAMPAIGN_ID, "event": "DELIVERED",  "event_timestamp": BASE_TS},
        {"receipt_id": "RCPT-TEST-00018", "communication_id": "COMM-CH-PUSH-000006",
         "campaign_id": DEMO_CAMPAIGN_ID, "event": "OPENED",     "event_timestamp": BASE_TS},
        # PUSH failed
        {"receipt_id": "RCPT-TEST-00019", "communication_id": "COMM-CH-PUSH-000007",
         "campaign_id": DEMO_CAMPAIGN_ID, "event": "DISPATCHED", "event_timestamp": BASE_TS},
        {"receipt_id": "RCPT-TEST-00020", "communication_id": "COMM-CH-PUSH-000007",
         "campaign_id": DEMO_CAMPAIGN_ID, "event": "FAILED",     "event_timestamp": BASE_TS},
        # WHATSAPP full funnel
        {"receipt_id": "RCPT-TEST-00021", "communication_id": "COMM-CH-WA-0000008",
         "campaign_id": DEMO_CAMPAIGN_ID, "event": "DISPATCHED", "event_timestamp": BASE_TS},
        {"receipt_id": "RCPT-TEST-00022", "communication_id": "COMM-CH-WA-0000008",
         "campaign_id": DEMO_CAMPAIGN_ID, "event": "DELIVERED",  "event_timestamp": BASE_TS},
        {"receipt_id": "RCPT-TEST-00023", "communication_id": "COMM-CH-WA-0000008",
         "campaign_id": DEMO_CAMPAIGN_ID, "event": "READ",       "event_timestamp": BASE_TS},
        {"receipt_id": "RCPT-TEST-00024", "communication_id": "COMM-CH-WA-0000008",
         "campaign_id": DEMO_CAMPAIGN_ID, "event": "CLICKED",    "event_timestamp": BASE_TS},
        # WHATSAPP delivered + read
        {"receipt_id": "RCPT-TEST-00025", "communication_id": "COMM-CH-WA-0000009",
         "campaign_id": DEMO_CAMPAIGN_ID, "event": "DISPATCHED", "event_timestamp": BASE_TS},
        {"receipt_id": "RCPT-TEST-00026", "communication_id": "COMM-CH-WA-0000009",
         "campaign_id": DEMO_CAMPAIGN_ID, "event": "DELIVERED",  "event_timestamp": BASE_TS},
        {"receipt_id": "RCPT-TEST-00027", "communication_id": "COMM-CH-WA-0000009",
         "campaign_id": DEMO_CAMPAIGN_ID, "event": "READ",       "event_timestamp": BASE_TS},
        # WHATSAPP delivered only
        {"receipt_id": "RCPT-TEST-00028", "communication_id": "COMM-CH-WA-0000010",
         "campaign_id": DEMO_CAMPAIGN_ID, "event": "DISPATCHED", "event_timestamp": BASE_TS},
        {"receipt_id": "RCPT-TEST-00029", "communication_id": "COMM-CH-WA-0000010",
         "campaign_id": DEMO_CAMPAIGN_ID, "event": "DELIVERED",  "event_timestamp": BASE_TS},
    ]

    receipts: pd.DataFrame = pd.DataFrame(raw_receipts)
    communications_df: pd.DataFrame = pd.DataFrame(
        [
            {"communication_id": "COMM-CH-EMAIL-00001", "channel": "EMAIL"},
            {"communication_id": "COMM-CH-EMAIL-00002", "channel": "EMAIL"},
            {"communication_id": "COMM-CH-EMAIL-00003", "channel": "EMAIL"},
            {"communication_id": "COMM-CH-SMS-000004", "channel": "SMS"},
            {"communication_id": "COMM-CH-SMS-000005", "channel": "SMS"},
            {"communication_id": "COMM-CH-PUSH-000006", "channel": "PUSH"},
            {"communication_id": "COMM-CH-PUSH-000007", "channel": "PUSH"},
            {"communication_id": "COMM-CH-WA-0000008", "channel": "WHATSAPP"},
            {"communication_id": "COMM-CH-WA-0000009", "channel": "WHATSAPP"},
            {"communication_id": "COMM-CH-WA-0000010", "channel": "WHATSAPP"},
        ]
    )
    print(f"\n  Synthetic receipt log built: {len(receipts):,} rows across 10 communications.")

    # ------------------------------------------------------------------
    # 1. Schema validation — simulate what load_receipts() enforces.
    # ------------------------------------------------------------------

    print(f"\n{'─' * 60}")
    print("  Schema validation")
    print("─" * 60)

    missing_cols: set[str] = set(RECEIPT_COLUMNS) - set(receipts.columns)
    assert not missing_cols, (
        f"[smoke_test] Synthetic data is missing columns: {missing_cols}"
    )
    print(f"  ✓ All required columns present: {RECEIPT_COLUMNS}")

    # ------------------------------------------------------------------
    # 2. Campaign metrics calculation.
    # ------------------------------------------------------------------

    print(f"\n{'─' * 60}")
    print("  Campaign metrics calculation")
    print("─" * 60)

    campaign_metrics: dict[str, Any] = calculate_campaign_metrics(receipts)

    delivery_rate: float = campaign_metrics["delivery_rate"]
    open_rate:     float = campaign_metrics["open_rate"]
    click_rate:    float = campaign_metrics["click_rate"]
    failure_rate:  float = campaign_metrics["failure_rate"]

    assert delivery_rate >= 0,   "[smoke_test] delivery_rate must be ≥ 0."
    assert delivery_rate <= 100, "[smoke_test] delivery_rate must be ≤ 100."
    assert open_rate     >= 0,   "[smoke_test] open_rate must be ≥ 0."
    assert open_rate     <= 100, "[smoke_test] open_rate must be ≤ 100."
    assert click_rate    >= 0,   "[smoke_test] click_rate must be ≥ 0."
    assert click_rate    <= 100, "[smoke_test] click_rate must be ≤ 100."
    assert failure_rate  >= 0,   "[smoke_test] failure_rate must be ≥ 0."
    assert failure_rate  <= 100, "[smoke_test] failure_rate must be ≤ 100."

    print(f"  ✓ delivery_rate  : {delivery_rate:.1f} %  (range assertion passed)")
    print(f"  ✓ open_rate      : {open_rate:.1f} %  (range assertion passed)")
    print(f"  ✓ click_rate     : {click_rate:.1f} %  (range assertion passed)")
    print(f"  ✓ failure_rate   : {failure_rate:.1f} %  (range assertion passed)")

    # ------------------------------------------------------------------
    # 3. Channel metrics calculation.
    # ------------------------------------------------------------------

    print(f"\n{'─' * 60}")
    print("  Channel metrics calculation")
    print("─" * 60)

    channel_metrics: pd.DataFrame = calculate_channel_metrics(receipts, communications_df)

    assert not channel_metrics.empty, (
        "[smoke_test] channel_metrics DataFrame must not be empty."
    )
    assert set(CHANNEL_METRIC_COLUMNS).issubset(set(channel_metrics.columns)), (
        f"[smoke_test] channel_metrics is missing required columns. "
        f"Expected: {CHANNEL_METRIC_COLUMNS}, got: {list(channel_metrics.columns)}"
    )

    expected_channels: set[str] = {"EMAIL", "SMS", "PUSH", "WHATSAPP"}
    found_channels: set[str]    = set(channel_metrics["channel"].unique())
    assert expected_channels == found_channels, (
        f"[smoke_test] Expected channels {expected_channels}, "
        f"but found {found_channels}."
    )

    print(f"  ✓ channel_metrics contains {len(channel_metrics)} channel row(s).")
    print(f"  ✓ Expected channels all present: {sorted(expected_channels)}")

    for _, row in channel_metrics.iterrows():
        ch: str = row["channel"]
        for metric in ("delivery_rate", "open_rate", "click_rate", "failure_rate"):
            val: float = float(row[metric])
            assert 0.0 <= val <= 100.0, (
                f"[smoke_test] {ch}.{metric} = {val} is outside [0, 100]."
            )
    print("  ✓ All channel metric values are within [0, 100].")

    # ------------------------------------------------------------------
    # 4. Known-value assertions to verify calculation correctness.
    #
    #    EMAIL: 3 dispatched, 2 delivered, 1 failed, 2 opened, 1 clicked.
    #    Expected:
    #      delivery_rate  = 2/3 * 100 = 66.67 %
    #      open_rate      = 2/2 * 100 = 100.00 %
    #      click_rate     = 1/2 * 100 = 50.00 %
    #      failure_rate   = 1/3 * 100 = 33.33 %
    # ------------------------------------------------------------------

    print(f"\n{'─' * 60}")
    print("  Known-value correctness assertions (EMAIL channel)")
    print("─" * 60)

    email_row: pd.Series = channel_metrics[
        channel_metrics["channel"] == "EMAIL"
    ].iloc[0]

    assert abs(email_row["delivery_rate"] - 66.67) < 0.01, (
        f"[smoke_test] EMAIL delivery_rate expected 66.67, "
        f"got {email_row['delivery_rate']}."
    )
    assert abs(email_row["open_rate"] - 100.0) < 0.01, (
        f"[smoke_test] EMAIL open_rate expected 100.0, "
        f"got {email_row['open_rate']}."
    )
    assert abs(email_row["click_rate"] - 50.0) < 0.01, (
        f"[smoke_test] EMAIL click_rate expected 50.0, "
        f"got {email_row['click_rate']}."
    )
    assert abs(email_row["failure_rate"] - 33.33) < 0.01, (
        f"[smoke_test] EMAIL failure_rate expected 33.33, "
        f"got {email_row['failure_rate']}."
    )
    print("  ✓ EMAIL delivery_rate  = 66.67 %  (verified)")
    print("  ✓ EMAIL open_rate      = 100.00 %  (verified)")
    print("  ✓ EMAIL click_rate     = 50.00 %  (verified)")
    print("  ✓ EMAIL failure_rate   = 33.33 %  (verified)")

    # ------------------------------------------------------------------
    # 5. Recommendations generation.
    # ------------------------------------------------------------------

    print(f"\n{'─' * 60}")
    print("  Recommendations generation")
    print("─" * 60)

    recommendations: list[str] = generate_recommendations(campaign_metrics)

    assert len(recommendations) > 0, (
        "[smoke_test] generate_recommendations must return at least one entry."
    )
    assert all(isinstance(r, str) for r in recommendations), (
        "[smoke_test] All recommendations must be strings."
    )
    assert all(len(r) > 0 for r in recommendations), (
        "[smoke_test] All recommendation strings must be non-empty."
    )

    print(f"  ✓ {len(recommendations)} recommendation(s) generated.")
    print("  ✓ All recommendations are non-empty strings.")

    # ------------------------------------------------------------------
    # 6. Empty DataFrame edge cases.
    # ------------------------------------------------------------------

    print(f"\n{'─' * 60}")
    print("  Empty DataFrame edge cases")
    print("─" * 60)

    empty_df:            pd.DataFrame   = pd.DataFrame(columns=RECEIPT_COLUMNS)
    empty_camp_metrics:  dict[str, Any] = calculate_campaign_metrics(empty_df)
    empty_chan_metrics:  pd.DataFrame   = calculate_channel_metrics(empty_df)
    empty_recs:          list[str]      = generate_recommendations(empty_camp_metrics)

    assert empty_camp_metrics["total_communications"] == 0, (
        "[smoke_test] Empty receipts should produce total_communications = 0."
    )
    assert empty_chan_metrics.empty, (
        "[smoke_test] Empty receipts should produce an empty channel_metrics DataFrame."
    )
    assert len(empty_recs) > 0, (
        "[smoke_test] generate_recommendations must always return at least one entry."
    )

    print("  ✓ calculate_campaign_metrics handles empty DataFrame correctly.")
    print("  ✓ calculate_channel_metrics returns empty DataFrame for empty input.")
    print("  ✓ generate_recommendations returns fallback recommendation for zero metrics.")

    # ------------------------------------------------------------------
    # 7. Determinism check — run both calculation functions twice.
    # ------------------------------------------------------------------

    print(f"\n{'─' * 60}")
    print("  Determinism verification")
    print("─" * 60)

    run1_camp: dict[str, Any] = calculate_campaign_metrics(receipts)
    run2_camp: dict[str, Any] = calculate_campaign_metrics(receipts)
    assert run1_camp == run2_camp, (
        "[smoke_test] calculate_campaign_metrics is not deterministic."
    )

    run1_chan: pd.DataFrame = calculate_channel_metrics(receipts, communications_df)
    run2_chan: pd.DataFrame = calculate_channel_metrics(receipts, communications_df)
    pd.testing.assert_frame_equal(
        run1_chan.reset_index(drop=True),
        run2_chan.reset_index(drop=True),
    )

    print("  ✓ calculate_campaign_metrics is deterministic across two runs.")
    print("  ✓ calculate_channel_metrics is deterministic across two runs.")

    # ------------------------------------------------------------------
    # 8. Print full summary.
    # ------------------------------------------------------------------

    print_summary(campaign_metrics, channel_metrics, recommendations)

    # ------------------------------------------------------------------
    # 9. Load from Receipt API output (best-effort; non-fatal if absent).
    # ------------------------------------------------------------------

    print(f"\n{'─' * 60}")
    print("  Receipt API integration (live file load)")
    print("─" * 60)

    try:
        live_receipts: pd.DataFrame = load_receipts()

        if live_receipts.empty:
            print(
                "  – No Receipt API output found at default path. "
                "Run Receipt API first to populate the event log."
            )
        else:
            live_camp_metrics: dict[str, Any] = calculate_campaign_metrics(live_receipts)
            live_chan_metrics: pd.DataFrame   = calculate_channel_metrics(live_receipts)
            live_recs:         list[str]      = generate_recommendations(live_camp_metrics)

            print(
                f"  ✓ Loaded {len(live_receipts):,} receipt rows from "
                f"Receipt API output."
            )
            print_summary(live_camp_metrics, live_chan_metrics, live_recs)

    except ValueError as exc:
        print(f"  ✗ Schema error loading live receipts: {exc}", file=sys.stderr)

    # ------------------------------------------------------------------
    # 10. Final result.
    # ------------------------------------------------------------------

    print(f"{'=' * 60}")
    print("  Smoke test complete — all assertions passed.")
    print(f"{'=' * 60}\n")


if __name__ == "__main__":
    main()